# Generated by Django 5.2.10 on 2026-02-01 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SEARCH_QUERY", "Search Query"),
                            ("SEARCH_RESULTS", "Search Results"),
                            ("PAGE_VIEW", "Page View"),
                            ("CONTENT_VIEW", "Content View"),
                            ("CONTENT_ACTION", "Content Action"),
                            ("USER_ACTION", "User Action"),
                            ("USER_AUTH", "User Authentication"),
                            ("SYSTEM_EVENT", "System Event"),
                            ("SECURITY_EVENT", "Security Event"),
                            ("SALE_EVENT", "Sale Event"),
                            ("FORM_SUBMIT", "Form Submit"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_name", models.CharField(max_length=255)),
                ("properties", models.JSONField(default=dict)),
                ("session_id", models.UUIDField(null=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "event_type", "created_at"],
                        name="analytics_e_store_i_3b8d78_idx",
                    ),
                    models.Index(
                        fields=["store", "created_at"],
                        name="analytics_e_store_i_556d81_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="analytics_e_user_id_30758e_idx",
                    ),
                    models.Index(fields=["session_id"], name="analytics_e_session_d46398_idx"),
                    models.Index(fields=["event_name"], name="analytics_e_event_n_299a11_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.CharField(db_index=True, max_length=255)),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("search_type", models.CharField(default="content", max_length=50)),
                ("session_id", models.UUIDField(null=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "query", "created_at"],
                        name="analytics_s_store_i_eee7a6_idx",
                    ),
                    models.Index(
                        fields=["store", "created_at"],
                        name="analytics_s_store_i_77346b_idx",
                    ),
                ],
            },
        ),
    ]
