# Generated by Django 5.2.10 on 2026-02-02 05:53

from django.db import migrations


def migrate_logs_data(apps, schema_editor):
    """Migrate existing LogEntry data to EventLog"""
    EventLog = apps.get_model("analytics", "EventLog")

    # Check if logs table exists
    try:
        LogEntry = apps.get_model("logs", "LogEntry")
    except LookupError:
        # logs app or model doesn't exist, skip migration
        return

    # Migrate existing LogEntry records to EventLog
    for log_entry in LogEntry.objects.all():
        EventLog.objects.create(
            store=log_entry.store,
            event_type=log_entry.event_type,
            event_name=log_entry.message or f"{log_entry.event_type} Event",
            properties={
                "level": log_entry.level,
                "entity_type": log_entry.entity_type,
                "entity_id": log_entry.entity_id,
                "page_url": log_entry.page_url,
                "referrer": log_entry.referrer,
                "is_suspicious": log_entry.is_suspicious,
                "risk_score": log_entry.risk_score,
                "original_metadata": log_entry.metadata,
            },
            user=log_entry.user,
            session_id=log_entry.session_id,
            ip_address=log_entry.ip_address,
            user_agent=log_entry.user_agent,
            request_id=log_entry.request_id,
            duration_ms=log_entry.duration_ms,
            created_at=log_entry.created_at,
        )


def reverse_migrate_logs_data(apps, schema_editor):
    """Reverse migration - data remains in EventLog"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_logs_data, reverse_migrate_logs_data),
    ]
