# Generated by Django 6.0.1 on 2026-01-28 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM_STARTUP", "System Startup"),
                            ("SYSTEM_ERROR", "System Error"),
                            ("USER_LOGIN", "User Login"),
                            ("USER_LOGOUT", "User Logout"),
                            ("USER_REGISTER", "User Registration"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("CONTENT_CREATE", "Content Created"),
                            ("CONTENT_UPDATE", "Content Updated"),
                            ("CONTENT_DELETE", "Content Deleted"),
                            ("CONTENT_PUBLISH", "Content Published"),
                            ("PAGE_VIEW", "Page View"),
                            ("CLICK", "Click Event"),
                            ("FORM_SUBMIT", "Form Submit"),
                            ("FILE_DOWNLOAD", "File Download"),
                            ("BOUNCE", "Bounce (quick exit)"),
                            ("LOGIN_FAILED", "Failed Login"),
                            ("SUSPICIOUS_ACTIVITY", "Suspicious Activity"),
                            ("RATE_LIMIT", "Rate Limit Exceeded"),
                            ("BLOCKED_IP", "IP Blocked"),
                            ("EMAIL_SEND_ATTEMPT", "Email Send Attempt"),
                            ("EMAIL_SEND_SUCCESS", "Email Send Success"),
                            ("EMAIL_SEND_FAILED", "Email Send Failed"),
                            ("EMAIL_OPENED", "Email Opened"),
                            ("EMAIL_CLICKED", "Email Clicked"),
                            ("API_CALL", "API Call"),
                            ("API_ERROR", "API Error"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("entity_type", models.CharField(blank=True, max_length=100)),
                ("entity_id", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("page_url", models.URLField(blank=True)),
                ("referrer", models.URLField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("is_suspicious", models.BooleanField(default=False)),
                ("risk_score", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="log_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "logs_entry",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["store", "event_type", "created_at"],
                        name="logs_entry_store_i_8fd8d4_idx",
                    ),
                    models.Index(
                        fields=["store", "created_at"], name="logs_entry_store_i_0145d0_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="logs_entry_user_id_9ffc0b_idx"
                    ),
                    models.Index(fields=["session_id"], name="logs_entry_session_3a638e_idx"),
                    models.Index(fields=["ip_address"], name="logs_entry_ip_addr_3edaff_idx"),
                    models.Index(fields=["is_suspicious"], name="logs_entry_is_susp_36d477_idx"),
                    models.Index(fields=["created_at"], name="logs_entry_created_4ad545_idx"),
                ],
            },
        ),
    ]
