# Generated by Django 6.0.1 on 2026-01-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetafieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "namespace",
                    models.CharField(help_text="Category for grouping fields", max_length=50),
                ),
                (
                    "key",
                    models.CharField(help_text="Unique identifier within namespace", max_length=50),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "True/False"),
                            ("date", "Date"),
                            ("url", "URL"),
                            ("json", "JSON"),
                            ("select", "Dropdown"),
                            ("multiselect", "Multi-select"),
                            ("image", "Image"),
                            ("file", "File"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_filterable", models.BooleanField(default=False)),
                ("is_sortable", models.BooleanField(default=False)),
                (
                    "options",
                    models.JSONField(
                        default=list, help_text="Options for select/multiselect fields"
                    ),
                ),
                (
                    "validations",
                    models.JSONField(
                        default=dict,
                        help_text="Validation rules (min_length, max_length, etc.)",
                    ),
                ),
                (
                    "content_types",
                    models.JSONField(default=list, help_text="Which models this field applies to"),
                ),
                (
                    "ui",
                    models.JSONField(
                        default=dict,
                        help_text="UI configuration (placeholder, help text, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "metafields_definition",
                "ordering": ["namespace", "key"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Metafield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_number", models.FloatField(blank=True, null=True)),
                ("value_boolean", models.BooleanField(blank=True, default=False)),
                ("value_date", models.DateTimeField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "metafields_value",
                "ordering": ["definition", "created_at"],
                "abstract": False,
            },
        ),
    ]
