# Generated by Django 5.2.10 on 2026-01-27 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("stores", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetafieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(max_length=64)),
                ("key", models.CharField(max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("json", "JSON"),
                            ("media", "Media Reference"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128)),
                ("description", models.TextField(blank=True)),
                ("validations", models.JSONField(blank=True, default=dict)),
                ("default_value", models.JSONField(blank=True, null=True)),
                ("options", models.JSONField(blank=True, default=list)),
                ("ui", models.JSONField(blank=True, default=dict)),
                ("is_required", models.BooleanField(default=False)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_filterable", models.BooleanField(default=False)),
                ("is_sortable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="metafield_definitions",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metafield_definitions",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metafield Definition",
                "verbose_name_plural": "Metafield Definitions",
            },
        ),
        migrations.CreateModel(
            name="Metafield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("value", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metafields",
                        to="stores.store",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metafields",
                        to="metafields.metafielddefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metafield",
                "verbose_name_plural": "Metafields",
            },
        ),
        migrations.AddIndex(
            model_name="metafielddefinition",
            index=models.Index(
                fields=["store", "namespace", "key"],
                name="metafields__store_i_bfadce_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="metafielddefinition",
            unique_together={("store", "namespace", "key")},
        ),
        migrations.AddIndex(
            model_name="metafield",
            index=models.Index(
                fields=["store", "content_type", "object_id"],
                name="metafields__store_i_eaae45_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metafield",
            index=models.Index(fields=["definition"], name="metafields__definit_da90d2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="metafield",
            unique_together={("content_type", "object_id", "definition")},
        ),
    ]
