# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("mediafile", "0001_initial"),
        ("metafields", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetafieldDefinition",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "namespace",
                    models.CharField(max_length=50, help_text="Category for grouping fields"),
                ),
                (
                    "key",
                    models.CharField(max_length=50, help_text="Unique identifier within namespace"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "True/False"),
                            ("date", "Date"),
                            ("url", "URL"),
                            ("json", "JSON"),
                            ("select", "Dropdown"),
                            ("multiselect", "Multi-select"),
                            ("image", "Image"),
                            ("file", "File"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_filterable", models.BooleanField(default=False)),
                ("is_sortable", models.BooleanField(default=False)),
                (
                    "options",
                    models.JSONField(
                        default=list, help_text="Options for select/multiselect fields"
                    ),
                ),
                (
                    "validations",
                    models.JSONField(
                        default=dict, help_text="Validation rules (min_length, max_length, etc.)"
                    ),
                ),
                (
                    "content_types",
                    models.JSONField(default=list, help_text="Which models this field applies to"),
                ),
                (
                    "ui",
                    models.JSONField(
                        default=dict, help_text="UI configuration (placeholder, help text, etc.)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metafield_definitions",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "metafields_definition",
                "unique_together": {("store", "namespace", "key")},
                "indexes": [
                    models.Index(
                        fields=["namespace", "key"], name="metafields_namespace__key_5b8c5c_idx"
                    ),
                    models.Index(fields=["is_visible"], name="metafields_is_visible_5b8c5c_idx"),
                    models.Index(
                        fields=["content_types"], name="metafields_content_types_5b8c5c_idx"
                    ),
                ],
                "ordering": ["namespace", "key"],
            },
        ),
        migrations.CreateModel(
            name="Metafield",
            fields=[
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="metafields.metafielddefinition",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_number", models.FloatField(blank=True, null=True)),
                ("value_boolean", models.BooleanField(blank=True, default=False)),
                ("value_date", models.DateTimeField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                (
                    "value_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mediafile.mediafile",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metafields",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "metafields_value",
                "unique_together": {("store", "definition", "content_type", "object_id")},
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="metafields_content_type__object_id_5b8c5c_idx",
                    ),
                    models.Index(
                        fields=["definition", "value_text"],
                        name="metafields_definition__value_text_5b8c5c_idx",
                    ),
                    models.Index(
                        fields=["definition", "value_number"],
                        name="metafields_definition__value_number_5b8c5c_idx",
                    ),
                ],
                "ordering": ["definition", "created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Metafield",
        ),
        migrations.DeleteModel(
            name="MetafieldDefinition",
        ),
    ]
