# Generated by Django 6.0.1 on 2026-01-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mediafile", "__first__"),
        ("metafields", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metafield",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="metafield",
            name="value_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mediafile.mediafile",
            ),
        ),
        migrations.AddField(
            model_name="metafielddefinition",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="metafield",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="metafields.metafielddefinition",
            ),
        ),
        migrations.AddIndex(
            model_name="metafielddefinition",
            index=models.Index(fields=["namespace", "key"], name="metafields__namespa_1e701c_idx"),
        ),
        migrations.AddIndex(
            model_name="metafielddefinition",
            index=models.Index(fields=["is_visible"], name="metafields__is_visi_48c3f1_idx"),
        ),
        migrations.AddIndex(
            model_name="metafielddefinition",
            index=models.Index(fields=["content_types"], name="metafields__content_3449b4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="metafielddefinition",
            unique_together={("store", "namespace", "key")},
        ),
        migrations.AddIndex(
            model_name="metafield",
            index=models.Index(
                fields=["content_type", "object_id"], name="metafields__content_307ae3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metafield",
            index=models.Index(
                fields=["definition", "value_text"], name="metafields__definit_4efd4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metafield",
            index=models.Index(
                fields=["definition", "value_number"], name="metafields__definit_970eeb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="metafield",
            unique_together={("store", "definition", "content_type", "object_id")},
        ),
    ]
