# Generated by Django 6.0.1 on 2026-01-28 10:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCardHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("activated", "Activated"),
                            ("redeemed", "Redeemed"),
                            ("refunded", "Refunded"),
                            ("expired", "Expired"),
                            ("voided", "Voided"),
                            ("updated", "Updated"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Gift Card History",
                "db_table": "giftcards_history",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GiftCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=12, unique=True)),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "gift_card_type",
                    models.CharField(
                        choices=[
                            ("digital", "Digital"),
                            ("physical", "Physical"),
                            ("promotional", "Promotional"),
                            ("refund", "Refund"),
                            ("loyalty", "Loyalty"),
                        ],
                        default="digital",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inactive", "Inactive"),
                            ("active", "Active"),
                            ("redeemed", "Redeemed"),
                            ("expired", "Expired"),
                            ("voided", "Voided"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("recipient_name", models.CharField(blank=True, max_length=100)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("sender_name", models.CharField(blank=True, max_length=100)),
                ("sender_email", models.EmailField(blank=True, max_length=254)),
                ("message", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_gift_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "giftcards_gift_card",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
