# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=12, unique=True)),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "gift_card_type",
                    models.CharField(
                        choices=[
                            ("digital", "Digital"),
                            ("physical", "Physical"),
                            ("promotional", "Promotional"),
                            ("refund", "Refund"),
                            ("loyalty", "Loyalty"),
                        ],
                        default="digital",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inactive", "Inactive"),
                            ("active", "Active"),
                            ("redeemed", "Redeemed"),
                            ("expired", "Expired"),
                            ("voided", "Voided"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("recipient_name", models.CharField(blank=True, max_length=100)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("sender_name", models.CharField(blank=True, max_length=100)),
                ("sender_email", models.EmailField(blank=True, max_length=254)),
                ("message", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_gift_cards",
                        to="auth.user",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_cards",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "giftcards_gift_card",
                "indexes": [
                    models.Index(fields=["store", "code"], name="giftcards_store__code_8a1c8f_idx"),
                    models.Index(
                        fields=["store", "status"], name="giftcards_store__status_8a1c8f_idx"
                    ),
                    models.Index(fields=["expires_at"], name="giftcards_expires_at_5b8c5c_idx"),
                    models.Index(fields=["code"], name="giftcards_code_5b8c5c_idx"),
                ],
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GiftCardHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("activated", "Activated"),
                            ("redeemed", "Redeemed"),
                            ("refunded", "Refunded"),
                            ("expired", "Expired"),
                            ("voided", "Voided"),
                            ("updated", "Updated"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.user",
                    ),
                ),
                (
                    "gift_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="giftcards.giftcard",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ecommerce.order",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_card_history",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "giftcards_history",
                "indexes": [
                    models.Index(
                        fields=["gift_card", "action"],
                        name="giftcards_gift_card__action_8a1c8f_idx",
                    ),
                    models.Index(
                        fields=["gift_card", "created_at"],
                        name="giftcards_gift_card__created_at_8a1c8f_idx",
                    ),
                    models.Index(
                        fields=["store", "action"], name="giftcards_store__action_8a1c8f_idx"
                    ),
                ],
                "ordering": ["-created_at"],
                "verbose_name_plural": "Gift Card History",
            },
        ),
    ]
