# Generated by Django 6.0.1 on 2026-01-28 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ecommerce", "__first__"),
        ("giftcards", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcard",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="giftcardhistory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="giftcardhistory",
            name="gift_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="giftcards.giftcard",
            ),
        ),
        migrations.AddField(
            model_name="giftcardhistory",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecommerce.order",
            ),
        ),
        migrations.AddField(
            model_name="giftcardhistory",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="stores.store",
            ),
        ),
        migrations.AddIndex(
            model_name="giftcard",
            index=models.Index(fields=["store", "code"], name="giftcards_g_store_i_e0f402_idx"),
        ),
        migrations.AddIndex(
            model_name="giftcard",
            index=models.Index(fields=["store", "status"], name="giftcards_g_store_i_3ad66d_idx"),
        ),
        migrations.AddIndex(
            model_name="giftcard",
            index=models.Index(fields=["expires_at"], name="giftcards_g_expires_6948e8_idx"),
        ),
        migrations.AddIndex(
            model_name="giftcard",
            index=models.Index(fields=["code"], name="giftcards_g_code_e0778a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="giftcard",
            unique_together={("store", "code")},
        ),
        migrations.AddIndex(
            model_name="giftcardhistory",
            index=models.Index(
                fields=["gift_card", "action"], name="giftcards_h_gift_ca_6d92e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="giftcardhistory",
            index=models.Index(
                fields=["gift_card", "created_at"], name="giftcards_h_gift_ca_acceca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="giftcardhistory",
            index=models.Index(fields=["store", "action"], name="giftcards_h_store_i_58d2bd_idx"),
        ),
    ]
