# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                ("original_filename", models.CharField(max_length=255)),
                ("file_extension", models.CharField(max_length=10)),
                ("file_size", models.PositiveIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("storage_path", models.CharField(max_length=512)),
                ("imagekit_id", models.CharField(blank=True, max_length=255, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_files",
                        to="mediafile.mediafolder",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to="auth.user",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "mediafiles_media_file",
                "indexes": [
                    models.Index(
                        fields=["store", "resource_type"],
                        name="mediafiles_store__resource_type_8a1c8f_idx",
                    ),
                    models.Index(
                        fields=["store", "folder"], name="mediafiles_store__folder_8a1c8f_idx"
                    ),
                    models.Index(fields=["created_at"], name="mediafiles_created_at_5b8c5c_idx"),
                    models.Index(fields=["file_size"], name="mediafiles_file_size_5b8c5c_idx"),
                ],
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaFolder",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="mediafile.mediafolder",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_folders",
                        to="auth.user",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_folders",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "mediafiles_media_folder",
                "unique_together": {("store", "parent", "slug")},
                "indexes": [
                    models.Index(fields=["store"], name="mediafiles_store_5b8c5c_idx"),
                    models.Index(fields=["parent"], name="mediafiles_parent_5b8c5c_idx"),
                    models.Index(fields=["created_at"], name="mediafiles_created_at_8a1c8f_idx"),
                ],
                "ordering": ["name"],
            },
        ),
    ]
