# Generated by Django 5.2.10 on 2026-02-01 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediafile", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("authenticated", "Authenticated"),
                    ("private", "Private"),
                ],
                default="authenticated",
                help_text="Who can access this media file",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["store", "visibility"], name="mediafiles__store_i_718c13_idx"
            ),
        ),
    ]
