# Generated by Django 6.0.1 on 2026-01-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(default="Default Theme", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
            ],
            options={
                "db_table": "themes_theme",
                "ordering": ["-is_active", "name"],
                "unique_together": {("store", "name")},
            },
        ),
        migrations.CreateModel(
            name="Typography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "base_font_size",
                    models.PositiveSmallIntegerField(
                        default=16, help_text="Base font size in pixels (16px is recommended)"
                    ),
                ),
                (
                    "font_smoothing",
                    models.CharField(
                        choices=[
                            ("antialiased", "Smooth (antialiased)"),
                            ("subpixel-antialiased", "Crisp (subpixel)"),
                            ("auto", "System Default"),
                        ],
                        default="antialiased",
                        max_length=50,
                    ),
                ),
                (
                    "font_family_sans_serif",
                    models.CharField(
                        default='system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
                        help_text="Sans-serif font family stack",
                        max_length=100,
                    ),
                ),
                (
                    "font_family_serif",
                    models.CharField(
                        default='Georgia, "Times New Roman", Times, serif',
                        help_text="Serif font family stack",
                        max_length=100,
                    ),
                ),
                (
                    "font_family_monospace",
                    models.CharField(
                        default='SFMono-Regular, Consolas, "Liberation Mono", Menlo, Monaco, Courier New, monospace',
                        help_text="Monospace font family stack",
                        max_length=100,
                    ),
                ),
                ("h1_font_size", models.PositiveSmallIntegerField(default=48)),
                ("h2_font_size", models.PositiveSmallIntegerField(default=36)),
                ("h3_font_size", models.PositiveSmallIntegerField(default=28)),
                ("h4_font_size", models.PositiveSmallIntegerField(default=24)),
                ("h5_font_size", models.PositiveSmallIntegerField(default=20)),
                ("h6_font_size", models.PositiveSmallIntegerField(default=16)),
                (
                    "heading_line_height",
                    models.DecimalField(decimal_places=2, default=1.2, max_digits=3),
                ),
                (
                    "body_line_height",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=3),
                ),
                (
                    "letter_spacing",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("font_weight_light", models.PositiveSmallIntegerField(default=300)),
                ("font_weight_normal", models.PositiveSmallIntegerField(default=400)),
                ("font_weight_medium", models.PositiveSmallIntegerField(default=500)),
                ("font_weight_bold", models.PositiveSmallIntegerField(default=700)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typography",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "db_table": "themes_typography",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.SlugField(max_length=100)),
                (
                    "template_role",
                    models.CharField(
                        choices=[
                            ("body", "Body"),
                            ("header", "Header"),
                            ("footer", "Footer"),
                            ("partial", "Partial"),
                            ("section", "Section"),
                        ],
                        default="body",
                        help_text="Defines the template's role in the layout system",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Template content (HTML or JSON)")),
                (
                    "content_type",
                    models.CharField(
                        choices=[("html", "HTML"), ("json", "JSON")], default="html", max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "db_table": "themes_template",
                "ordering": ["name"],
                "unique_together": {("theme", "key")},
            },
        ),
        migrations.CreateModel(
            name="StyleClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "default_css",
                    models.JSONField(
                        default=dict, help_text="Default CSS properties for this style class"
                    ),
                ),
                (
                    "light_css",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Light mode CSS overrides (merges with default_css)",
                    ),
                ),
                (
                    "dark_css",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dark mode CSS overrides (merges with default_css)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_classes",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "db_table": "themes_style_class",
                "ordering": ["name"],
                "unique_together": {("theme", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ColorScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.SlugField(max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "colors",
                    models.JSONField(blank=True, default=dict, help_text="Light mode colors"),
                ),
                (
                    "dark_colors",
                    models.JSONField(blank=True, default=dict, help_text="Dark mode colors"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_schemes",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "db_table": "themes_color_scheme",
                "ordering": ["name"],
                "unique_together": {("theme", "key")},
            },
        ),
    ]
