# Generated by Django 4.2 on 2024-01-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(default="Default Theme", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
            ],
            options={
                "db_table": "themes_theme",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="ColorScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.SlugField(max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "colors",
                    models.JSONField(blank=True, default=dict, help_text="Light mode colors"),
                ),
                (
                    "dark_colors",
                    models.JSONField(blank=True, default=dict, help_text="Dark mode colors"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_schemes",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "db_table": "themes_color_scheme",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Typography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "base_font_size",
                    models.PositiveSmallIntegerField(
                        default=16, help_text="Base font size in pixels (16px is recommended)"
                    ),
                ),
                (
                    "font_smoothing",
                    models.CharField(
                        choices=[
                            ("antialiased", "Smooth (antialiased)"),
                            ("subpixel-antialiased", "Crisp (subpixel)"),
                            ("auto", "System Default"),
                        ],
                        default="antialiased",
                        max_length=50,
                    ),
                ),
                (
                    "font_primary",
                    models.CharField(
                        default="Inter, system-ui, -apple-system, sans-serif",
                        help_text="Primary font family (used for headings and UI)",
                        max_length=255,
                    ),
                ),
                (
                    "font_secondary",
                    models.CharField(
                        default="Inter, system-ui, -apple-system, sans-serif",
                        help_text="Secondary font family (used for body text)",
                        max_length=255,
                    ),
                ),
                (
                    "font_accent",
                    models.CharField(
                        default="'Inter Variable', sans-serif",
                        help_text="Accent font family (used for special elements)",
                        max_length=255,
                    ),
                ),
                (
                    "font_mono",
                    models.CharField(
                        default="'JetBrains Mono', 'Fira Code', monospace",
                        help_text="Monospace font family",
                        max_length=255,
                    ),
                ),
                ("font_weight_light", models.PositiveIntegerField(default=300)),
                ("font_weight_normal", models.PositiveIntegerField(default=400)),
                ("font_weight_medium", models.PositiveIntegerField(default=500)),
                ("font_weight_semibold", models.PositiveIntegerField(default=600)),
                ("font_weight_bold", models.PositiveIntegerField(default=700)),
                (
                    "line_height_none",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
                ),
                (
                    "line_height_tight",
                    models.DecimalField(decimal_places=2, default=1.25, max_digits=3),
                ),
                (
                    "line_height_snug",
                    models.DecimalField(decimal_places=2, default=1.375, max_digits=3),
                ),
                (
                    "line_height_normal",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=3),
                ),
                (
                    "line_height_relaxed",
                    models.DecimalField(decimal_places=2, default=1.625, max_digits=3),
                ),
                (
                    "line_height_loose",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=3),
                ),
                (
                    "letter_spacing_tighter",
                    models.DecimalField(decimal_places=3, default=-0.05, max_digits=4),
                ),
                (
                    "letter_spacing_tight",
                    models.DecimalField(decimal_places=3, default=-0.025, max_digits=4),
                ),
                (
                    "letter_spacing_normal",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                (
                    "letter_spacing_wide",
                    models.DecimalField(decimal_places=3, default=0.025, max_digits=4),
                ),
                (
                    "letter_spacing_wider",
                    models.DecimalField(decimal_places=3, default=0.05, max_digits=4),
                ),
                (
                    "letter_spacing_widest",
                    models.DecimalField(decimal_places=3, default=0.1, max_digits=4),
                ),
                (
                    "headings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Advanced heading configurations (h1-h6)",
                    ),
                ),
                (
                    "paragraph_margin",
                    models.JSONField(
                        blank=True, default=dict, help_text="Margin settings for paragraphs"
                    ),
                ),
                (
                    "text_transform_headings",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("uppercase", "Uppercase"),
                            ("lowercase", "Lowercase"),
                            ("capitalize", "Capitalize"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "font_display",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("block", "Block"),
                            ("swap", "Swap"),
                            ("fallback", "Fallback"),
                            ("optional", "Optional"),
                        ],
                        default="swap",
                        help_text="Controls how fonts are displayed while loading",
                        max_length=20,
                    ),
                ),
                (
                    "text_rendering",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("optimizeSpeed", "Optimize Speed"),
                            ("optimizeLegibility", "Optimize Legibility"),
                            ("geometricPrecision", "Geometric Precision"),
                        ],
                        default="optimizeLegibility",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
                (
                    "theme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typography",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "db_table": "themes_typography",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StyleClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "default_css",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default CSS properties for this style class",
                    ),
                ),
                (
                    "light_css",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Light mode CSS overrides (merges with default_css)",
                    ),
                ),
                (
                    "dark_css",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dark mode CSS overrides (merges with default_css)",
                    ),
                ),
                (
                    "version_css",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Version-specific CSS overrides (e.g., {'v1': {...}, 'v2': {...}})",
                    ),
                ),
                (
                    "media_queries",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Responsive styles (e.g., {'sm': {...}, 'md': {...}, 'lg': {...}})",
                    ),
                ),
                (
                    "pseudo_classes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Pseudo-class styles (e.g., {'hover': {...}, 'focus': {...}, 'active': {...}})",
                    ),
                ),
                (
                    "animations",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Animation properties (e.g., {'transition': 'all 0.3s ease', 'animation': 'fadeIn 0.5s'})",
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True,
                        help_text="Raw CSS for complex styles that can't be expressed in JSON",
                    ),
                ),
                (
                    "version_custom_css",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Version-specific raw CSS (e.g., {'v1': '...', 'v2': '...'})",
                    ),
                ),
                (
                    "css_variables",
                    models.JSONField(
                        blank=True, default=dict, help_text="CSS variables specific to this class"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System style classes cannot be deleted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_classes",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "db_table": "themes_style_class",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Layout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content_slots",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Defines content slots and their default content",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "footer_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_as_footer",
                        to="themes.template",
                    ),
                ),
                (
                    "header_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_as_header",
                        to="themes.template",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layouts",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "db_table": "themes_layout",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.SlugField(max_length=100)),
                (
                    "template_role",
                    models.CharField(
                        choices=[
                            ("body", "Body"),
                            ("header", "Header"),
                            ("footer", "Footer"),
                            ("partial", "Partial"),
                            ("section", "Section"),
                        ],
                        default="body",
                        help_text="Defines the template's role in the layout system",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "content",
                    models.TextField(
                        help_text="HTML template with variables (Django template syntax)"
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(blank=True, help_text="Custom CSS for this template"),
                ),
                (
                    "custom_js",
                    models.TextField(blank=True, help_text="Custom JavaScript for this template"),
                ),
                (
                    "version_css",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Version-specific CSS (e.g., {'v1': '...', 'v2': '...'})",
                    ),
                ),
                (
                    "version_js",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Version-specific JavaScript (e.g., {'v1': '...', 'v2': '...'})",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Default meta title for pages using this template",
                        max_length=200,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Default meta description for pages using this template",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Default meta keywords for pages using this template",
                        max_length=500,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default template for this type and role"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System templates cannot be deleted"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True, default=dict, help_text="Available variables in this template"
                    ),
                ),
                (
                    "requires",
                    models.JSONField(
                        blank=True, default=list, help_text="Required components or templates"
                    ),
                ),
                (
                    "preview_image",
                    models.URLField(blank=True, help_text="Preview image for template selection"),
                ),
                (
                    "preview_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Sample data for template preview"
                    ),
                ),
                (
                    "cache_duration",
                    models.PositiveIntegerField(default=300, help_text="Cache duration in seconds"),
                ),
                ("minify_html", models.BooleanField(default=False, help_text="Minify HTML output")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layout",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default layout for this template (body templates only)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates_using_this_layout",
                        to="themes.layout",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "db_table": "themes_template",
                "ordering": ["template_role", "name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="theme",
            unique_together={("store", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="colorscheme",
            unique_together={("theme", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="styleclass",
            unique_together={("theme", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="layout",
            unique_together={("theme", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="template",
            unique_together={("theme", "key")},
        ),
    ]
