# Generated by Django 6.0.2 on 2026-02-06 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="storemembership",
            name="store",
        ),
        migrations.RemoveField(
            model_name="storemembership",
            name="user",
        ),
    ]
