# Generated by Django 6.0.2 on 2026-02-06 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_store_owner_remove_storemembership_store_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Store",
        ),
        migrations.DeleteModel(
            name="StoreMembership",
        ),
    ]
