# Generated by Django 6.0.2 on 2026-02-06 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(help_text="URL-friendly identifier", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional category description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this category is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="posts.category",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
                "unique_together": {("store", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(help_text="URL-friendly identifier", max_length=200)),
                ("excerpt", models.TextField(blank=True, help_text="Short summary or excerpt")),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Main content (HTML, Markdown, or JSON)"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("html", "HTML"), ("markdown", "Markdown"), ("json", "JSON")],
                        default="html",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Whether this post is featured"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, help_text="When this post was published", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(blank=True, related_name="posts", to="posts.category"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField(help_text="Comment content")),
                (
                    "is_approved",
                    models.BooleanField(default=True, help_text="Whether this comment is approved"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, help_text="Whether this comment is public"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="posts.comment",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique identifier for this post type within the store"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this post type"
                    ),
                ),
                (
                    "is_builtin",
                    models.BooleanField(
                        default=False, help_text="System post types that cannot be deleted"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this post type is active"),
                ),
                (
                    "schema",
                    models.JSONField(
                        blank=True,
                        help_text="JSON schema for custom fields (future use)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_types",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Type",
                "verbose_name_plural": "Post Types",
                "ordering": ["-is_builtin", "name"],
                "unique_together": {("store", "key")},
            },
        ),
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="posts.posttype",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(help_text="URL-friendly identifier", max_length=100)),
                ("description", models.TextField(blank=True, help_text="Optional tag description")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this tag is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
                "unique_together": {("store", "slug")},
            },
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="posts", to="posts.tag"),
        ),
        migrations.CreateModel(
            name="PostMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(help_text="Metadata key", max_length=100)),
                (
                    "value",
                    models.JSONField(
                        help_text="Metadata value (can be string, number, object, etc.)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Meta",
                "verbose_name_plural": "Post Meta",
                "ordering": ["key"],
                "unique_together": {("post", "key")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("store", "post_type", "slug")},
        ),
    ]
