# Generated by Django 5.2.10 on 2026-02-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_fix_store_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="posttype",
            name="allow_categories",
            field=models.BooleanField(
                default=True, help_text="Whether posts of this type can have categories"
            ),
        ),
        migrations.AddField(
            model_name="posttype",
            name="allow_comments",
            field=models.BooleanField(
                default=True, help_text="Whether posts of this type can have comments"
            ),
        ),
        migrations.AddField(
            model_name="posttype",
            name="allow_tags",
            field=models.BooleanField(
                default=True, help_text="Whether posts of this type can have tags"
            ),
        ),
    ]
