# Generated by Django 5.2.10 on 2026-02-06 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_posttype_allow_categories_posttype_allow_comments_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this post",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this post",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
