# Generated by Django 5.2.10 on 2026-02-06 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_post_created_by_post_updated_by"),
        ("stores", "0001_initial"),
        ("themes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostTypeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "post_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_templates",
                        to="posts.posttype",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_type_templates",
                        to="stores.store",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="themes.template",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_type_templates",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Type Template",
                "verbose_name_plural": "Post Type Templates",
                "ordering": ["post_type__name", "theme__name"],
                "unique_together": {("store", "post_type", "theme")},
            },
        ),
    ]
