services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: cms-backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.development
      - PYTHONUNBUFFERED=1
    env_file:
      - ../.env
    depends_on:
      - redis
    volumes:
      - ../backend:/app
      - backend_media:/app/media
      - backend_static:/app/staticfiles
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:7-alpine
    container_name: cms-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  backend_media:
  backend_static:
