# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "form_id",
                    models.CharField(
                        help_text="Unique identifier for the form", max_length=50, unique=True
                    ),
                ),
                ("fields", models.JSONField(default=dict, help_text="Form field definitions")),
                (
                    "settings",
                    models.JSONField(default=dict, help_text="Form settings and configuration"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "save_to_database",
                    models.BooleanField(default=True, help_text="Save submissions to database"),
                ),
                ("send_email_notifications", models.BooleanField(default=True)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("seo_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_forms",
                        to="auth.user",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_templates",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "forms_form_template",
                "unique_together": {("store", "slug"), ("store", "form_id")},
                "indexes": [
                    models.Index(fields=["store", "status"], name="forms_store__status_8a1c8f_idx"),
                    models.Index(
                        fields=["store", "is_active"], name="forms_store__is_active_8a1c8f_idx"
                    ),
                    models.Index(fields=["form_id"], name="forms_form_id_5b8c5c_idx"),
                ],
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                ("submission_id", models.CharField(max_length=50, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "form_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="forms.formtemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_submissions",
                        to="auth.user",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_submissions",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "forms_form_submissions",
                "unique_together": {("store", "submission_id")},
                "indexes": [
                    models.Index(
                        fields=["store", "form_template", "status"],
                        name="forms_store__form_template__status_8a1c8f_idx",
                    ),
                    models.Index(fields=["user", "status"], name="forms_user__status_5b8c5c_idx"),
                    models.Index(fields=["submitted_at"], name="forms_submitted_at_5b8c5c_idx"),
                ],
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                ("title", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("body_html", models.TextField()),
                ("body_text", models.TextField(blank=True)),
                ("headers", models.JSONField(default=dict, help_text="Custom email headers")),
                (
                    "variables",
                    models.JSONField(default=dict, help_text="Template variables documentation"),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("admin", "Form Admin"),
                            ("owner", "Form Owner"),
                            ("custom", "Custom Email"),
                            ("submitter", "Form Submitter"),
                        ],
                        default="admin",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(blank=True, help_text="Custom recipient email"),
                ),
                (
                    "auto_detect_recipient",
                    models.BooleanField(default=True, help_text="Auto-detect from form fields"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_templates",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "forms_email_template",
                "indexes": [
                    models.Index(
                        fields=["store", "recipient_type"],
                        name="forms_store__recipient_type_8a1c8f_idx",
                    ),
                    models.Index(fields=["is_active"], name="forms_is_active_5b8c5c_idx"),
                ],
                "ordering": ["title"],
            },
        ),
    ]
