# Generated by Django 6.0.1 on 2026-01-28 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("forms", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_submissions",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="formsubmissiondata",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to="forms.formsubmission",
            ),
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_templates",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="form_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="forms.formtemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmissiondata",
            index=models.Index(
                fields=["submission", "field_order"],
                name="forms_form__submiss_0e914b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="formtemplate",
            index=models.Index(fields=["store", "slug"], name="forms_form__store_i_601e3b_idx"),
        ),
        migrations.AddIndex(
            model_name="formtemplate",
            index=models.Index(fields=["store", "status"], name="forms_form__store_i_f6cef1_idx"),
        ),
        migrations.AddIndex(
            model_name="formtemplate",
            index=models.Index(
                fields=["store", "is_active"], name="forms_form__store_i_3fc926_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formtemplate",
            index=models.Index(fields=["form_id"], name="forms_form__form_id_ce449a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="formtemplate",
            unique_together={("store", "form_id"), ("store", "slug")},
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["store", "form_template", "status"],
                name="forms_form__store_i_c52493_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["form_template", "submission_id"],
                name="forms_form__form_te_239c0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(fields=["user", "status"], name="forms_form__user_id_dff54e_idx"),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(fields=["submitted_at"], name="forms_form__submitt_1c72fb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="formsubmission",
            unique_together={("store", "submission_id")},
        ),
    ]
