# Generated by Django 6.0.1 on 2026-01-28 14:06

import secrets

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(max_length=2048)),
                (
                    "method",
                    models.CharField(
                        choices=[("POST", "POST"), ("PUT", "PUT")],
                        default="POST",
                        max_length=10,
                    ),
                ),
                (
                    "secret",
                    models.CharField(default=secrets.token_urlsafe, max_length=255),
                ),
                ("verify_ssl", models.BooleanField(default=True)),
                ("event_types", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
            ],
            options={
                "db_table": "webhooks_webhook",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("event_id", models.CharField(blank=True, max_length=100)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response_status", models.PositiveIntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhooks.webhook",
                    ),
                ),
            ],
            options={
                "db_table": "webhooks_delivery",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("content", "Content"),
                            ("ecommerce", "Ecommerce"),
                            ("user", "User"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("schema", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
            ],
            options={
                "db_table": "webhooks_event",
                "ordering": ["store", "category", "event_type"],
            },
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(
                fields=["store", "is_active"], name="webhooks_we_store_i_a777f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(fields=["created_at"], name="webhooks_we_created_9104e4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="webhook",
            unique_together={("store", "url")},
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["store", "webhook", "status"],
                name="webhooks_de_store_i_e8e66d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["store", "event_type"], name="webhooks_de_store_i_fae506_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["store", "triggered_at"], name="webhooks_de_store_i_99a7e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["store", "next_retry_at"], name="webhooks_de_store_i_5cf383_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["webhook", "status"], name="webhooks_de_webhook_573ad2_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["event_type"], name="webhooks_de_event_t_3c8b8e_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["triggered_at"], name="webhooks_de_trigger_f1ee6c_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["next_retry_at"], name="webhooks_de_next_re_0b2c29_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(fields=["store", "category"], name="webhooks_ev_store_i_8f32ab_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["store", "event_type"], name="webhooks_ev_store_i_08b353_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["category", "event_type"], name="webhooks_ev_categor_570cfc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="webhookevent",
            unique_together={("store", "event_type")},
        ),
    ]
