# Generated by Django 6.0.1 on 2026-01-28 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="stores.store",
                verbose_name="store",
            ),
        ),
        migrations.AddField(
            model_name="storeuser",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_users",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="storeuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to.",
                related_name="custom_user_groups",
                related_query_name="custom_user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="custom_user_permissions",
                related_query_name="custom_user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="store_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="accounts.storeuser",
                verbose_name="store user",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["store", "name"], name="accounts_ro_store_i_fef2bf_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["store", "is_active"], name="accounts_ro_store_i_a39aca_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("store", "name")},
        ),
        migrations.AddIndex(
            model_name="storeuser",
            index=models.Index(fields=["store", "role"], name="accounts_st_store_i_9e9bad_idx"),
        ),
        migrations.AddIndex(
            model_name="storeuser",
            index=models.Index(fields=["user", "role"], name="accounts_st_user_id_9b2379_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="storeuser",
            unique_together={("user", "store")},
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["store_user", "action"], name="accounts_us_store_u_7ce728_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["created_at"], name="accounts_us_created_e16cd7_idx"),
        ),
    ]
