# Generated by Django 5.2.11 on 2026-02-04 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_userpreferences_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_password_reset_token",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["token", "expires_at"],
                        name="accounts_pa_token_c2575f_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="accounts_pa_user_id_59a21c_idx",
                    ),
                    models.Index(fields=["expires_at"], name="accounts_pa_expires_682fbf_idx"),
                ],
            },
        ),
    ]
