# Generated by Django 6.0.1 on 2026-01-28 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("toggle", "Toggle (Like/Unlike)"),
                            ("single", "Single (Upvote only)"),
                            ("rating", "Rating (1-5 stars)"),
                            ("counter", "Counter (View count)"),
                        ],
                        default="toggle",
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=20)),
                (
                    "content_types",
                    models.JSONField(default=list, help_text="Which models this action applies to"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("allow_anonymous", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "entities_entity_action",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntityInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("value", models.JSONField(blank=True, default=dict)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="entities.entityaction",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "entities_entity_interaction",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="entityaction",
            index=models.Index(
                fields=["store", "is_active"], name="entities_en_store_i_765b9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entityaction",
            index=models.Index(fields=["content_types"], name="entities_en_content_358702_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="entityaction",
            unique_together={("store", "slug")},
        ),
        migrations.AddIndex(
            model_name="entityinteraction",
            index=models.Index(
                fields=["action", "content_type", "object_id"],
                name="entities_en_action__a6ca84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entityinteraction",
            index=models.Index(fields=["user", "is_active"], name="entities_en_user_id_300acc_idx"),
        ),
        migrations.AddIndex(
            model_name="entityinteraction",
            index=models.Index(fields=["created_at"], name="entities_en_created_ee4961_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="entityinteraction",
            unique_together={("store", "action", "user", "content_type", "object_id")},
        ),
    ]
