# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityAction",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("toggle", "Toggle (Like/Unlike)"),
                            ("single", "Single (Upvote only)"),
                            ("rating", "Rating (1-5 stars)"),
                            ("counter", "Counter (View count)"),
                        ],
                        default="toggle",
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("content_types", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("allow_anonymous", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_actions",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "entities_entity_action",
                "unique_together": {("store", "slug")},
                "indexes": [
                    models.Index(
                        fields=["store", "is_active"], name="entities_store__is_active_8a1c8f_idx"
                    ),
                    models.Index(
                        fields=["content_types"], name="entities_content_types_5b8c5c_idx"
                    ),
                ],
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EntityInteraction",
            fields=[
                ("value", models.JSONField(blank=True, default=dict)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="entities.entityaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_interactions",
                        null=True,
                        blank=True,
                        to="auth.user",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_interactions",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "entities_entity_interaction",
                "unique_together": {("store", "action", "user", "content_type", "object_id")},
                "indexes": [
                    models.Index(
                        fields=["action", "content_type", "object_id"],
                        name="entities_action__content_type__object_id_8a1c8f_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"], name="entities_user__is_active_5b8c5c_idx"
                    ),
                    models.Index(fields=["created_at"], name="entities_created_at_5b8c5c_idx"),
                ],
                "ordering": ["-created_at"],
            },
        ),
    ]
