# Generated by Django 6.0.1 on 2026-01-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("index_name", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "content_types",
                    models.JSONField(
                        default=list,
                        help_text="List of content types to index: ['Page', 'Post', 'Product']",
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        default=dict, help_text="Field mappings and search configuration"
                    ),
                ),
                (
                    "facets",
                    models.JSONField(default=list, help_text="Facet configuration for filtering"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_reindexed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "search_index",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.CharField(db_index=True, max_length=255)),
                (
                    "search_type",
                    models.CharField(
                        choices=[("content", "Content"), ("product", "Product"), ("all", "All")],
                        max_length=50,
                    ),
                ),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("filters", models.JSONField(default=dict)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "search_query",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=255)),
                ("content_type", models.CharField(max_length=50)),
                ("object_id", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("excerpt", models.TextField(blank=True)),
                ("url", models.URLField(max_length=500)),
                ("score", models.FloatField(default=0.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-score", "-updated_at"],
            },
        ),
    ]
