# Generated by Django 6.0.1 on 2026-01-28 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("search", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="searchindex",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_logs",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="searchquery",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="searchquery",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="searchresult",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cached_search_results",
                to="stores.store",
            ),
        ),
        migrations.AddIndex(
            model_name="searchindex",
            index=models.Index(fields=["store"], name="search_inde_store_i_e0dd33_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="searchindex",
            unique_together={("store", "name")},
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(fields=["store", "query"], name="search_quer_store_i_86e864_idx"),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(fields=["created_at"], name="search_quer_created_366af0_idx"),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(fields=["search_type"], name="search_quer_search__3447fa_idx"),
        ),
        migrations.AddIndex(
            model_name="searchresult",
            index=models.Index(fields=["query", "store"], name="search_sear_query_8dd536_idx"),
        ),
        migrations.AddIndex(
            model_name="searchresult",
            index=models.Index(
                fields=["content_type", "object_id"], name="search_sear_content_86c0e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchresult",
            index=models.Index(fields=["score"], name="search_sear_score_fe5992_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="searchresult",
            unique_together={("query", "store", "content_type", "object_id")},
        ),
    ]
