# Generated by Django 6.0.1 on 2026-01-28 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mediafile", "__first__"),
        ("posts", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="featured_posts",
                to="mediafile.mediafile",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postrevision",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postrevision",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="posttype",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="posts.posttype",
            ),
        ),
        migrations.AddField(
            model_name="taxonomy",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="posts", to="posts.taxonomy"),
        ),
        migrations.AddField(
            model_name="term",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="posts.term",
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="taxonomy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terms",
                to="posts.taxonomy",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="tagged_posts", to="posts.term"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "is_approved", "created_at"],
                name="posts_comme_post_id_5b904c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent", "is_approved"], name="posts_comme_parent__f066a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["user", "created_at"], name="posts_comme_user_id_c1d8b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["is_approved", "is_spam"], name="posts_comme_is_appr_fa9f70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["created_at"], name="posts_comme_created_f825cb_idx"),
        ),
        migrations.AddIndex(
            model_name="postrevision",
            index=models.Index(
                fields=["post", "revision_number"],
                name="posts_post__post_id_0946dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postrevision",
            index=models.Index(fields=["created_at"], name="posts_post__created_2045f7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="postrevision",
            unique_together={("post", "revision_number")},
        ),
        migrations.AddIndex(
            model_name="posttype",
            index=models.Index(fields=["slug"], name="posts_post__slug_155bf1_idx"),
        ),
        migrations.AddIndex(
            model_name="posttype",
            index=models.Index(fields=["is_system"], name="posts_post__is_syst_d4f700_idx"),
        ),
        migrations.AddIndex(
            model_name="taxonomy",
            index=models.Index(fields=["taxonomy_type"], name="posts_taxon_taxonom_ab55c3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="taxonomy",
            unique_together={("slug",)},
        ),
        migrations.AddIndex(
            model_name="term",
            index=models.Index(fields=["taxonomy"], name="posts_term_taxonom_097949_idx"),
        ),
        migrations.AddIndex(
            model_name="term",
            index=models.Index(fields=["parent"], name="posts_term_parent__aefd33_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="term",
            unique_together={("slug",)},
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["slug"], name="posts_post_slug_59b922_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "published_at"], name="posts_post_status_384c95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["post_type"], name="posts_post_post_ty_5d6bf8_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["published_at"], name="posts_post_publish_04eb5b_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["created_at"], name="posts_post_created_dadbfe_idx"),
        ),
    ]
