# Generated by Django 5.2.10 on 2026-02-02 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="search_vector",
        ),
    ]
