# Generated by Django 5.2.10 on 2026-02-01 15:27

import core.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("password_reset", "Password Reset"),
                            ("email_verification", "Email Verification"),
                            ("welcome", "Welcome"),
                            ("order_confirmation", "Order Confirmation"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("html_content", models.TextField()),
                ("text_content", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
            ],
            options={
                "db_table": "smtp_email_template",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("dropped", "Dropped"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("html_content", models.TextField(blank=True)),
                ("text_content", models.TextField(blank=True)),
                (
                    "tracking_id",
                    models.UUIDField(default=django.utils.timezone.now, unique=True),
                ),
                ("message_id", models.CharField(blank=True, max_length=255)),
                ("is_tracked", models.BooleanField(default=False)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="smtp.emailtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "smtp_email_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("dropped", "Dropped"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_data", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="smtp.emaillog",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
            ],
            options={
                "db_table": "smtp_email_tracking",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmtpConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("gmail", "Gmail"),
                            ("outlook", "Outlook"),
                            ("sendgrid", "SendGrid"),
                            ("mailgun", "Mailgun"),
                            ("ses", "Amazon SES"),
                            ("custom", "Custom SMTP"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField(default=587)),
                ("username", models.EmailField(max_length=254)),
                ("password", core.fields.EncryptedCharField(max_length=255)),
                ("use_tls", models.BooleanField(default=True)),
                ("use_ssl", models.BooleanField(default=False)),
                ("daily_limit", models.PositiveIntegerField(default=1000)),
                ("hourly_limit", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
            ],
            options={
                "db_table": "smtp_configuration",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="emaillog",
            name="smtp_config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="smtp.smtpconfiguration",
            ),
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(
                fields=["store", "template_type"], name="smtp_email__store_i_058ac6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(
                fields=["store", "is_active"], name="smtp_email__store_i_d9e2d0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailtemplate",
            unique_together={("store", "name")},
        ),
        migrations.AddIndex(
            model_name="emailtracking",
            index=models.Index(
                fields=["store", "event_type", "created_at"],
                name="smtp_email__store_i_2033b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailtracking",
            index=models.Index(
                fields=["email_log", "event_type"],
                name="smtp_email__email_l_7271b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="smtpconfiguration",
            index=models.Index(
                fields=["store", "is_active"], name="smtp_config_store_i_4edd0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smtpconfiguration",
            index=models.Index(fields=["store", "provider"], name="smtp_config_store_i_3a89de_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="smtpconfiguration",
            unique_together={("store", "name")},
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["store", "status", "created_at"],
                name="smtp_email__store_i_7eefec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["store", "to_email"], name="smtp_email__store_i_6c3bee_idx"),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["tracking_id"], name="smtp_email__trackin_fcd620_idx"),
        ),
    ]
