# Generated by Django 5.2.11 on 2026-02-04 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="search_vector",
        ),
    ]
