# Generated by Django

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0002_add_search_vector"),
    ]

    operations = [
        # Create CollectionProduct through model
        migrations.CreateModel(
            name="CollectionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_products",
                        to="ecommerce.productcollection",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_products",
                        to="ecommerce.product",
                    ),
                ),
            ],
            options={
                "db_table": "ecommerce_collection_products",
                "unique_together": {("collection", "product")},
                "ordering": ["position"],
            },
        ),
    ]
