# Generated by Django 5.2.10 on 2026-02-06 09:39

import apps.themes.models

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(default="Default Theme", max_length=100)),
                ("key", models.SlugField(help_text="Unique key for this theme", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description of the theme"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Whether this is the default theme for the store"
                    ),
                ),
                (
                    "typography",
                    models.JSONField(
                        default=apps.themes.models.get_default_typography,
                        help_text="Typography settings as JSON",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "themes_theme",
                "ordering": ["-is_default", "name"],
                "unique_together": {("store", "key"), ("store", "name")},
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.SlugField(max_length=100)),
                (
                    "template_role",
                    models.CharField(
                        choices=[
                            ("body", "Body"),
                            ("header", "Header"),
                            ("footer", "Footer"),
                            ("partial", "Partial"),
                            ("section", "Section"),
                        ],
                        default="body",
                        help_text="Defines the template's role in the layout system",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Template content (HTML or JSON)")),
                (
                    "content_type",
                    models.CharField(
                        choices=[("html", "HTML"), ("json", "JSON")], default="html", max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "db_table": "themes_template",
                "ordering": ["name"],
                "unique_together": {("theme", "key")},
            },
        ),
        migrations.CreateModel(
            name="StyleClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "default_css",
                    models.JSONField(
                        default=dict, help_text="Default CSS properties for this style class"
                    ),
                ),
                (
                    "light_css",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Light mode CSS overrides (merges with default_css)",
                    ),
                ),
                (
                    "dark_css",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dark mode CSS overrides (merges with default_css)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_classes",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "db_table": "themes_style_class",
                "ordering": ["name"],
                "unique_together": {("theme", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Layout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content_slots",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Defines content slots and their default content",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
                (
                    "footer_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_as_footer",
                        to="themes.template",
                    ),
                ),
                (
                    "header_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_as_header",
                        to="themes.template",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layouts",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "db_table": "themes_layout",
                "ordering": ["name"],
                "unique_together": {("theme", "key")},
            },
        ),
        migrations.CreateModel(
            name="ColorScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.SlugField(help_text="Unique key for this color scheme", max_length=100),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this color scheme", max_length=100
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Whether this is the default color scheme"
                    ),
                ),
                (
                    "colors",
                    models.JSONField(
                        default=apps.themes.models.get_default_colors,
                        help_text="Light mode colors as JSON",
                    ),
                ),
                (
                    "dark_colors",
                    models.JSONField(
                        default=apps.themes.models.get_default_dark_colors,
                        help_text="Dark mode colors as JSON",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_schemes",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "db_table": "themes_color_scheme",
                "ordering": ["-is_default", "name"],
                "unique_together": {("theme", "key"), ("theme", "name")},
            },
        ),
    ]
