# Generated by Django 5.2.10 on 2026-02-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("themes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("any", "Any"),
                    ("page", "Page"),
                    ("post", "Post"),
                    ("blog", "Blog"),
                    ("policy", "Policy"),
                    ("product", "Product"),
                    ("category", "Category"),
                ],
                default="any",
                help_text="Intended content type for this body template (page, post, policy, etc.)",
                max_length=50,
            ),
        ),
    ]
