# Generated by Django 5.2.10 on 2026-02-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("themes", "0002_template_template_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="template_type",
            field=models.CharField(
                default="any",
                help_text="Intended content type for this body template (PostType key or 'any' for generic)",
                max_length=100,
            ),
        ),
    ]
