# Generated by Django 6.0.1 on 2026-01-28 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "access_code",
                    models.CharField(editable=False, max_length=6, unique=True),
                ),
                (
                    "verification_token",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "store_type",
                    models.CharField(
                        choices=[
                            ("ecommerce", "E-commerce"),
                            ("blog", "Blog"),
                            ("portfolio", "Portfolio"),
                            ("corporate", "Corporate"),
                            ("other", "Other"),
                        ],
                        default="ecommerce",
                        max_length=20,
                    ),
                ),
                ("domain", models.URLField(blank=True, null=True, unique=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="stores/logos/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="stores/favicons/"),
                ),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                ("facebook_pixel_id", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                (
                    "bootstrap_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if bootstrap process has completed successfully",
                    ),
                ),
                (
                    "bootstrap_phase",
                    models.CharField(
                        blank=True,
                        help_text="Current phase of the bootstrap process",
                        max_length=50,
                    ),
                ),
                (
                    "bootstrap_error",
                    models.TextField(
                        blank=True,
                        help_text="Any errors that occurred during bootstrap",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stores_store",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="My Store", max_length=255)),
                ("site_description", models.TextField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("shipping_enabled", models.BooleanField(default=True)),
                (
                    "free_shipping_threshold",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("custom_settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_settings",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "stores_settings",
            },
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["slug"], name="stores_stor_slug_e2ab60_idx"),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["status"], name="stores_stor_status_d56e36_idx"),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["owner"], name="stores_stor_owner_i_731905_idx"),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["domain"], name="stores_stor_domain_9b7928_idx"),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["created_at"], name="stores_stor_created_f1ef67_idx"),
        ),
    ]
