# Generated by Django 5.2.11 on 2026-02-04 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediafile", "0002_mediafile_visibility_and_more"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="favicon",
            field=models.ForeignKey(
                blank=True,
                help_text="Store favicon image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="store_favicons",
                to="mediafile.mediafile",
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Store logo image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="store_logos",
                to="mediafile.mediafile",
            ),
        ),
    ]
